version: '2.1'

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/go/src/app
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
    ports:
      - 5432:5432
  redis:
    image: redis